#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/dns_client

- name: Installer resolvconf
  apt:
    name: resolvconf
    state: present
    update_cache: yes

- name: Configurer /etc/resolv.conf
  copy:
    dest: /etc/resolv.conf
    content: |
      search techvault.fr
      nameserver 172.16.0.116
    mode: '0644'

- name: Empêcher la réécriture de resolv.conf
  command: chattr +i /etc/resolv.conf
  ignore_errors: yes
